"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['ui/tkinter_stopwatch.py']
DATA_FILES = []
OPTIONS = {'iconfile': 'images/stopwatch.icns'}

setup(
    app=APP,
    name="StopWatch",
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
